#!/bin/bash

# function matrix () {
    # NAME
    # matrix - do matrix stuff
    # SYNOPSIS
    #   matrix 

    # dims ()
    # {
    #     echo this is the dims
    # }

    # if [$1 = "dims"]
    # then 
    #     dims()
    # fi
# }

      dims ()
    {
        echo this is the dims
    }
    # dims

    if [ "$1" == "dims" ]
    then 
        dims
    fi